### ISSUE TITLE
Oppo R9s seems can't decrypt, and returns xml.etree.ElementTree.ParseError 

### ISSUE THREAD

**Issue by Hinokami-Kagura** [bkerler/oppo_decrypt#76]
Maybe the Oppo R9s Ofp have different xml from A57t?

Traceback (most recent call last):
  File "/media/data/oppo_decrypt-master/ofp_qc_decrypt.py", line 347, in <module>
    main()
  File "/media/data/oppo_decrypt-master/ofp_qc_decrypt.py", line 322, in main
    root = ET.fromstring(xml)
  File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 1343, in XML
    return parser.close()
xml.etree.ElementTree.ParseError: no element found: line 140, column 13

Refer from #17 

Firmware location :  [CPH1607EX_11_A.11_170221] https://drive.google.com/file/d/1whoc8q2OXCj--OZV-ZZnq7Pp2Y2xcGKZ/view

**Comment by TipzRickyCheung** [comment]
@Hinokami-Kagura Fixed in #92
