### ISSUE TITLE
TypeError: 'iv' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by rajatgupta1998** [bkerler/oppo_decrypt#9]
Hi, I am trying a Realme firmware, but it fails here, I don't have python knowledge, so not sure what to do here:

`Traceback (most recent call last):
  File "ops_extract.py", line 252, in <module>
    main()
  File "ops_extract.py", line 182, in main
    pagesize,key,iv,data=generatekey2(filename)
  File "ops_extract.py", line 92, in generatekey2
    pagesize,data=extract_xml(filename,key,iv)
  File "ops_extract.py", line 121, in extract_xml
    dec=aes_cfb(data,key,iv)
  File "ops_extract.py", line 134, in aes_cfb
    ctx = AES.new(key, AES.MODE_CFB, iv=iv, segment_size=128)
  File "/home/rajatgupta1998/.local/lib/python3.6/site-packages/Crypto/Cipher/AES.py", line 95, in new
    return AESCipher(key, *args, **kwargs)
  File "/home/rajatgupta1998/.local/lib/python3.6/site-packages/Crypto/Cipher/AES.py", line 59, in __init__
    blockalgo.BlockAlgo.__init__(self, _AES, key, *args, **kwargs)
  File "/home/rajatgupta1998/.local/lib/python3.6/site-packages/Crypto/Cipher/blockalgo.py", line 141, in __init__
    self._cipher = factory.new(key, *args, **kwargs)
TypeError: 'iv' is an invalid keyword argument for this function
`

**Comment by rajatgupta1998** [comment]
Used pycryptodome instead of pycrypto. :P
